CREATE TABLE IF NOT EXISTS  users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(20) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role ENUM('ADMIN','EMPLOYEE','CUSTOMER') NOT NULL DEFAULT 'CUSTOMER'
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT NOW(),
    estimated_at DATETIME NULL,
    status ENUM('PENDING','PROCESSING','READY','DELIVERED','CANCELED') DEFAULT 'PENDING',
    order_price DOUBLE NOT NULL DEFAULT 0,
    delivery_price DOUBLE NOT NULL DEFAULT 0,
    total_price DOUBLE NOT NULL DEFAULT 0,

    FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
