CREATE TABLE IF NOT EXISTS  user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(20) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role ENUM('ADMIN','EMPLOYEE','CUSTOMER') DEFAULT 'CUSTOMER'
);

CREATE TABLE IF NOT EXISTS `order` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT NOW(),
    estimated_at DATETIME NULL,
    status ENUM('PENDING','PROCESSING','READY','DELIVERED','CANCELED') DEFAULT 'PENDING',
    order_price DOUBLE NOT NULL DEFAULT 0,
    delivery_price DOUBLE NOT NULL DEFAULT 0,
    total_price DOUBLE NOT NULL DEFAULT 0,

    FOREIGN KEY (user_id) REFERENCES user(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS stock_item (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        image_URL VARCHAR(200) ,
        name VARCHAR(100) NOT NULL,
        category ENUM('INGREDIENT','PRODUCT') DEFAULT'INGREDIENT',
        quantity DOUBLE NOT NULL DEFAULT 0,
        unit ENUM('KG','G','PIECE','L','ML')

);

CREATE TABLE  IF NOT EXISTS menu_product (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    product_category ENUM('PIZZA','SAUCE','DRINK'),
    price DOUBLE NOT NULL DEFAULT 0
);
